import Foundation

// Stage 3.5: incoming URLs from UIDocumentPicker live in a security-scoped
// container — we have to pair start/stopAccessingSecurityScopedResource and
// copy the bytes into our Documents/ sandbox before the scope ends.
// Dispatching is by file extension (the picker filter already restricts the
// set, but a fallback type means we might still see anything that looks like
// public.data, so re-check before we touch the filesystem):
//   .sis / .sisx   →  Documents/sis/<name>
//   .ttf / .otf    →  Documents/data/fonts/<name>
//   .zip           →  Documents/roms/<basename>/  (unzip)
//   *.rom / *.ROM  →  Documents/roms/<basename>/data/roms/<lowercased>/SYM.ROM
//                     (bare ROM image — minimal device tree is generated by
//                      mountRomNamed: if/when we land 3.4 follow-up)
final class ImportRouter {
    static let shared = ImportRouter()

    private var documentsRoot: String {
        NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true).first ?? NSHomeDirectory()
    }

    func ingest(urls: [URL]) -> String {
        var ok = 0
        var skipped: [String] = []
        for url in urls {
            // The picker hands back security-scoped URLs — we have to pair
            // start/stop or the copy will fail with permission denied.
            let scoped = url.startAccessingSecurityScopedResource()
            defer { if scoped { url.stopAccessingSecurityScopedResource() } }
            do {
                try ingest(url: url)
                ok += 1
            } catch {
                skipped.append("\(url.lastPathComponent): \(error.localizedDescription)")
            }
        }
        if skipped.isEmpty {
            return "Imported \(ok) item(s)."
        }
        return "Imported \(ok) item(s); \(skipped.count) skipped: \(skipped.joined(separator: "; "))"
    }

    private enum ImportError: LocalizedError {
        case unsupportedExtension(String)
        case zipUnsupported

        var errorDescription: String? {
            switch self {
            case .unsupportedExtension(let ext): return "unsupported file type .\(ext)"
            case .zipUnsupported: return "ROM .zip import lands in 3.5 follow-up — unzip externally for now"
            }
        }
    }

    private func ingest(url: URL) throws {
        let name = url.lastPathComponent
        let ext = url.pathExtension.lowercased()
        let fm = FileManager.default
        switch ext {
        case "sis", "sisx":
            let dst = (documentsRoot as NSString).appendingPathComponent("sis/\(name)")
            try copyReplacing(url: url, to: dst, fm: fm)
        case "ttf", "otf":
            let fontsDir = (documentsRoot as NSString).appendingPathComponent("data/fonts")
            try fm.createDirectory(atPath: fontsDir, withIntermediateDirectories: true)
            let dst = (fontsDir as NSString).appendingPathComponent(name)
            try copyReplacing(url: url, to: dst, fm: fm)
        case "zip":
            // miniz lives in the C++ side; the zip-extract path will surface
            // through a new Obj-C bridge in the 3.4 follow-up so that ROM
            // bundles can be authored without scripts/seed_ios_simulator_-
            // documents.sh. For now, surface a clear error instead of dropping
            // a half-imported tree.
            throw ImportError.zipUnsupported
        case "rom":
            let baseName = (url.deletingPathExtension().lastPathComponent)
            let firm = baseName.lowercased()
            let romDir = (documentsRoot as NSString).appendingPathComponent("roms/\(baseName)/data/roms/\(firm)")
            try fm.createDirectory(atPath: romDir, withIntermediateDirectories: true)
            try copyReplacing(url: url, to: (romDir as NSString).appendingPathComponent("SYM.ROM"), fm: fm)
        default:
            throw ImportError.unsupportedExtension(ext)
        }
    }

    private func copyReplacing(url: URL, to dst: String, fm: FileManager) throws {
        // Ensure parent exists.
        let parent = (dst as NSString).deletingLastPathComponent
        try fm.createDirectory(atPath: parent, withIntermediateDirectories: true)
        if fm.fileExists(atPath: dst) {
            try fm.removeItem(atPath: dst)
        }
        try fm.copyItem(at: url, to: URL(fileURLWithPath: dst))
    }
}
