#!/usr/bin/env python3
"""Generate src/emu/ios/Bridge/CpuSmokeBlob.h from a hand-picked A32 sequence.

The blob is deliberately small and self-contained: pure register arithmetic
ending in a `bkpt #0` so dyncom raises `exception_type_breakpoint` and we
can stop from the bridge's exception handler. (`udf #0` would be cleaner
semantically but dyncom's decoder calls CITRA_IGNORE_EXIT on decode
failure, which would abort the process before our handler ever runs.)
No memory accesses outside the code page, no kernel.

Encodings below are written by hand and double-checked against the ARMv7-A
encoding tables. Each instruction's expected effect is recorded so the test
harness can diff register-by-register.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path


# (encoding, asm-source, post-condition comment)
PROGRAM: list[tuple[int, str, str]] = [
    (0xE3A00001, "mov r0, #1",         "r0 = 1"),
    (0xE3A01002, "mov r1, #2",         "r1 = 2"),
    (0xE3A02003, "mov r2, #3",         "r2 = 3"),
    (0xE3A03004, "mov r3, #4",         "r3 = 4"),
    (0xE0800001, "add r0, r0, r1",     "r0 = 3"),
    (0xE0822003, "add r2, r2, r3",     "r2 = 7"),
    (0xE0820000, "add r0, r2, r0",     "r0 = 10"),
    (0xE1A06100, "mov r6, r0, lsl #2", "r6 = 40"),
    (0xE1200070, "bkpt #0",            "raises breakpoint exception"),
]

# Expected register state when dyncom raises the undef exception, with
# initial registers other than r13/r14/r15 zeroed and CPSR=USER32MODE (0x10).
EXPECTED_REGS: list[int] = [
    10,  # r0
    2,   # r1
    7,   # r2
    4,   # r3
    0,   # r4
    0,   # r5
    40,  # r6
    0,   # r7
    0,   # r8
    0,   # r9
    0,   # r10
    0,   # r11
    0,   # r12
]

# r13/r14/r15 are set by the harness; we don't pin them in the header.

CODE_BASE_VADDR = 0x0000_1000  # arbitrary, but page-aligned
PAGE_SIZE = 0x1000


def render_header() -> str:
    lines: list[str] = []
    lines.append("// SPDX-License-Identifier: GPL-3.0-or-later")
    lines.append("// Generated by scripts/gen_ios_cpu_smoke.py — do not hand edit.")
    lines.append("//")
    lines.append("// A tiny A32 program used by CpuSmokeBridge to verify the dyncom")
    lines.append("// interpreter actually executes on iOS. The blob ends in an undefined")
    lines.append("// instruction so dyncom raises exception_type_undefined_inst and stops.")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <array>")
    lines.append("#include <cstddef>")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("namespace eka2l1::ios::smoke {")
    lines.append("")
    lines.append(f"    inline constexpr std::uint32_t CODE_BASE_VADDR = 0x{CODE_BASE_VADDR:08X}u;")
    lines.append(f"    inline constexpr std::size_t   PAGE_SIZE       = 0x{PAGE_SIZE:X}u;")
    lines.append("")
    lines.append("    // Terminator: bkpt #0 (raises exception_type_breakpoint). The")
    lines.append("    // dyncom handler that fires it captures the post-bkpt PC at")
    lines.append("    // CODE_BASE_VADDR + (len-1)*4 and then calls core->stop() to halt.")
    lines.append("")
    lines.append("    // Instructions, little-endian 32-bit words. Source listing:")
    for word, asm, post in PROGRAM:
        lines.append(f"    //   0x{word:08X}  {asm:<24}; {post}")
    lines.append("    inline constexpr std::array<std::uint32_t, "
                 f"{len(PROGRAM)}> CODE_WORDS = {{")
    for word, asm, _ in PROGRAM:
        lines.append(f"        0x{word:08X}u,  // {asm}")
    lines.append("    };")
    lines.append("")
    lines.append("    // Register snapshot expected the moment dyncom raises bkpt.")
    lines.append("    // R13/R14/R15 are filled in by the harness, not pinned here.")
    lines.append("    inline constexpr std::array<std::uint32_t, 13> EXPECTED_R0_R12 = {")
    for value in EXPECTED_REGS:
        lines.append(f"        0x{value:08X}u,")
    lines.append("    };")
    lines.append("")
    lines.append("    // PC value at the moment of the bkpt raise:")
    lines.append("    //   CODE_BASE_VADDR + offset-of(udf) = base + (len-1)*4.")
    lines.append("    inline constexpr std::uint32_t EXPECTED_PC ="
                 f" CODE_BASE_VADDR + 0x{(len(PROGRAM) - 1) * 4:X}u;")
    lines.append("")
    lines.append("} // namespace eka2l1::ios::smoke")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    here = Path(__file__).resolve().parent.parent
    target = here / "src" / "emu" / "ios" / "Bridge" / "CpuSmokeBlob.h"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_header())
    print(f"wrote {target.relative_to(here)} ({target.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
